---
title: "BCTS papers"
output:
  distill::distill_article:
    toc: false
    toc_depth: 4
  html_document:
    df_print: paged
---

The BCTS system was established to help prioritise weed targets in South Africa for
biocontrol. For information on the development and application of the system see papers
below:

**Paper 1, Downey et al. 2021** <insert_url_when_available> - Prioritisation of targets for weed biological control I: 

A review of existing prioritisation schemes and development of a system for South Africa.
This paper identified and reviewed twelve previous systems developed to prioritise plant
targets for biocontrol. This review streamlined the development and testing of the BCTS
system in South Africa.

**Paper 2, Paterson et al. 2021** <insert_url_when_available> - Prioritisation of targets for weed biological control II: 

The South African Biological Control Target Selection System. This paper outlined the BCTS system. The BCTS is built of the previous systems and uses thirteen attributes to present the highest predictive powers to rank potential target plants as biocontrol targets.

**Paper 3, Canavan et al. 2021** <insert_url_when_available> - Prioritisation of targets for weed biological control III:

A tool to identify the next targets for biological control in South Africa and set priorities for
resource allocation. This paper applies the BCTS to 299 target plants listed on the National Environmental
Management Biodiversity Act (NEMBA) in South Africa. A list of top priorities species are
presented that represent good investments for biocontrol when funds are available.